using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebAPI_IDH.Models
{
    public partial class Calculates
    {
        public long? BeContMorahist60d6mTar0 { get; set; }
        public long? BeContMorahist180d12mCom { get; set; }
        public long? BeRefMoraactual30Tar1500 { get; set; }
        public long? BeSaldomoraact90Telco { get; set; }
        public double? BeSaldomoraact30Ban500 { get; set; }
        public long? BeContMorahist30d12mBan1000 { get; set; }
        public long? BeRefMoraactual90Imf { get; set; }
        public long? BeContMorahist60d12mCom1000 { get; set; }
        public long? BeContCalifIv36mBan { get; set; }
        public long? BeRefMoraactual60Ban2000 { get; set; }
        public long? BeContMorahist90d6mImf { get; set; }
        public long? BePeorCalif24mTar { get; set; }
        public long? BeRefMoraactual60Com1500 { get; set; }
        public long? BeContMorahist60d24mImf0 { get; set; }
        public long? BeContMorahist180d6mImf { get; set; }
        public long? BeContMorahist120d12mTelco { get; set; }
        public long? BeRefMoraactualTelco602000 { get; set; }
        public long? BeContMorahist90d24mBan { get; set; }
        public long? BeContMorahist30d12mImf1000 { get; set; }
        public long? BeContMorahist30d24mImf0 { get; set; }
        public long? BeContCalifIi36mTar { get; set; }
        public long? BeContMorahist90d36mImf { get; set; }
        public long? BePeorCalif12mTar { get; set; }
        public long? BeContMorahist180d12mTelco { get; set; }
        public long? BeContMorahist30d6mBan0 { get; set; }
        public long? BeSaldomoraact30Telco0 { get; set; }
        public long? BeContCalifIi12mBan { get; set; }
        public long? BeContMorahist60d36mBan0 { get; set; }
        public long? BeContMorahist180d12mTar { get; set; }
        public long? BeContMorahist150d12mTelco { get; set; }
        public long? BeRefMoraactual150Ban { get; set; }
        public long? BeSaldoMoraact60dTar0 { get; set; }
        public long? BeSaldoMoraact150Tar { get; set; }
        public long? BeContMorahist30d12mTar0 { get; set; }
        public long? BeSaldomoraact90Imf { get; set; }
        public long? BeRefMoraactual60Ban0 { get; set; }
        public long? BeContMorahist30d36mBan0 { get; set; }
        public long? BeSaldomoraact60Imf1500 { get; set; }
        public long? BeSaldomoraact180Com { get; set; }
        public long? BeTarCalificacionActual { get; set; }
        public long? BeRefMoraactual30Ban1500 { get; set; }
        public long? BeSaldomoraact30Telco1500 { get; set; }
        public string BeScore { get; set; }
        public double? BeSaldomoraact60Ban1500 { get; set; }
        public long? BeContMorahist90d6mBan { get; set; }
        public long? BeContMorahist120d36mBan { get; set; }
        public long? BeContMorahist180d12mImf { get; set; }
        public long? BeContMorahist60d6mTar1000 { get; set; }
        public long? BeSaldomoraact60Imf0 { get; set; }
        public double? BeSaldomoraact60Ban500 { get; set; }
        public long? BePeorCalif12mBan { get; set; }
        public long? BeRefMoraactual90Ban { get; set; }
        public long? BeContMorahist60d24mCom0 { get; set; }
        public double? BeSaldovencBan { get; set; }
        public long? BeContMorahist150d6mBan { get; set; }
        public long? BeContMorahist60d24mImf1000 { get; set; }
        public long? BeContMorahist90d24mImf { get; set; }
        public long? BeContCalifIii36mBan { get; set; }
        public long? BeSaldomoraact120Telco { get; set; }
        public long? BeRefMoraactualTelco300 { get; set; }
        public long? BeContMorahist60d24mTar1000 { get; set; }
        public long? BeContMorahist180d6mCom { get; set; }
        public long? BeContCalifIii24mBan { get; set; }
        public long? BeRefMoraactualCobroadminTelco { get; set; }
        public long? BeContCalifCfm12mTar { get; set; }
        public long? BeSaldomoraact60Imf2000 { get; set; }
        public long? BeRefMoraactual150Imf { get; set; }
        public long? BeContMorahist90d24mTelco { get; set; }
        public long? BeSaldoMoraact30dTar2000 { get; set; }
        public long? BeContCalifIv36mTar { get; set; }
        public long? BeContMorahist30d6mTelco0 { get; set; }
        public long? BeRefMoraactualTelco90 { get; set; }
        public long? BeContMorahist120d6mTelco { get; set; }
        public long? BeSaldomoraact60Com1500 { get; set; }
        public long? BeContMorahist30d36mCom1000 { get; set; }
        public long? BeContMorahist30d12mTelco0 { get; set; }
        public long? BeContMorahist90d36mBan { get; set; }
        public long? BeRefMoraactual60Tar2000 { get; set; }
        public long? BeSaldomoraact30Imf1500 { get; set; }
        public long? BeContMorahist120d24mBan { get; set; }
        public long? BeContMorahist30d24mTelco1000 { get; set; }
        public long? BeSaldoMoraact60dTar2000 { get; set; }
        public long? BeContMorahist30d24mCom0 { get; set; }
        public long? BeRefMoraactualTelco601000 { get; set; }
        public double? BeSaldomoraact90Ban { get; set; }
        public long? BeContCalifIi24mBan { get; set; }
        public long? BePeorCalif24mBan { get; set; }
        public long? BeSaldomoraact180Imf { get; set; }
        public long? BeRefMoraactual30Tar0 { get; set; }
        public long? BeContMorahist180d6mTar { get; set; }
        public long? BeRefMoraactual60Imf1500 { get; set; }
        public long? BeContMorahist90d12mImf { get; set; }
        public long? BeRefMoraactualCobroadminCom { get; set; }
        public long? BeContMorahist180d36mTar { get; set; }
        public long? BeContCalifCfm24mTar { get; set; }
        public long? BeContCalifI36mBan { get; set; }
        public long? BeContMorahist30d12mTar1000 { get; set; }
        public long? BeContCalifV24mTar { get; set; }
        public long? BeSaldomoraact60Com2000 { get; set; }
        public long? BeRefMoraactualTelco180 { get; set; }
        public double? BeSaldomoraact60Ban0 { get; set; }
        public long? BeContMorahist90d24mCom { get; set; }
        public long? BeContMorahist30d24mCom1000 { get; set; }
        public long? BeContMorahist90d12mTelco { get; set; }
        public long? BeContMorahist60d12mTelco0 { get; set; }
        public long? BeContMorahist60d24mTar0 { get; set; }
        public long? BeRefMoraactual180Imf { get; set; }
        public long? BeContMorahist60d6mTelco0 { get; set; }
        public long? BeRefMoraactual30Tar2000 { get; set; }
        public long? BeContMorahist180d36mCom { get; set; }
        public long? BeRefMoraactual30Tar500 { get; set; }
        public long? BeSaldomoraact30Com1500 { get; set; }
        public long? BeContCalifI24mBan { get; set; }
        public long? BeContMorahist120d36mTelco { get; set; }
        public long? BeContMorahist60d12mTar1000 { get; set; }
        public long? BeCalificacionActual { get; set; }
        public long? BeContCalifIv12mBan { get; set; }
        public long? BePeorCalif36mBan { get; set; }
        public long? BeRefMoraactual60Imf1000 { get; set; }
        public long? BeContMorahist60d6mImf0 { get; set; }
        public long? BeSaldoMoraact30dTar500 { get; set; }
        public long? BeContMorahist180d36mTelco { get; set; }
        public double? BeSaldomoraact180Ban { get; set; }
        public long? BeRefMoraactual30Imf1500 { get; set; }
        public long? BeContMorahist60d12mBan0 { get; set; }
        public long? BeContMorahist90d24mTar { get; set; }
        public long? BeContMorahist30d6mBan1000 { get; set; }
        public long? BeContMorahist30d12mCom0 { get; set; }
        public long? BeRefMoraactual180Tar { get; set; }
        public long? BeSaldomoraact30Com0 { get; set; }
        public long? BeContMorahist150d24mTar { get; set; }
        public long? BePeorCalif36mTar { get; set; }
        public long? BeContMorahist30d12mImf0 { get; set; }
        public long? BeContCalifCfm12mBan { get; set; }
        public long? BeRefMoraactual30Com1000 { get; set; }
        public long? BeContCalifIv12mTar { get; set; }
        public long? BeRefMoraactual30Tar1000 { get; set; }
        public long? BeContMorahist60d36mBan1000 { get; set; }
        public long? BeContMorahist180d6mBan { get; set; }
        public long? BeContMorahist60d6mTelco1000 { get; set; }
        public long? BeContMorahist60d12mImf1000 { get; set; }
        public long? BeContMorahist30d6mTelco1000 { get; set; }
        public long? BeContMorahist60d6mCom0 { get; set; }
        public long? BeContMorahist90d12mBan { get; set; }
        public long? BeRefMoraactual60Tar1000 { get; set; }
        public long? BeRefMoraactualCobroadminImf { get; set; }
        public long? BeContMorahist60d24mBan1000 { get; set; }
        public long? BeRefMoraactual120Com { get; set; }
        public long? BeContMorahist90d6mCom { get; set; }
        public long? BeSaldomoraact60Telco1000 { get; set; }
        public long? BeRefMoraactual60Imf2000 { get; set; }
        public long? BeSaldoMoraact60dTar1000 { get; set; }
        public long? BeContMorahist120d12mCom { get; set; }
        public long? BeSaldomoraact30Imf0 { get; set; }
        public long? BeRefMoraactual180Com { get; set; }
        public long? BeRefMoraactual30Imf2000 { get; set; }
        public long? BeContMorahist30d36mBan1000 { get; set; }
        public long? BeContMorahist180d36mImf { get; set; }
        public long? BeContMorahist60d12mTelco1000 { get; set; }
        public long? BeRefMoraactual60Tar500 { get; set; }
        public long? BeContMorahist30d24mTelco0 { get; set; }
        public long? BeSaldomoraact180Telco { get; set; }
        public long? BeContMorahist150d24mCom { get; set; }
        public long? BeContMorahist120d36mTar { get; set; }
        public long? BeRefMoraactualTelco301000 { get; set; }
        public double? BeScoreProm { get; set; }
        public long? BeContCalifIi24mTar { get; set; }
        public long? BeContCalifI36mTar { get; set; }
        public long? BeSaldoMoraact60dTar500 { get; set; }
        public long? BeRefMoraactual60Ban1500 { get; set; }
        public long? BeContMorahist120d36mImf { get; set; }
        public long? BeRefMoraactual60Tar0 { get; set; }
        public long? BeContMorahist30d12mTelco1000 { get; set; }
        public long? BeSaldoMoraact30dTar1500 { get; set; }
        public long? BeContMorahist30d24mImf1000 { get; set; }
        public long? BeContCalifIii36mTar { get; set; }
        public long? BeContMorahist90d6mTar { get; set; }
        public long? BeContMorahist60d36mCom0 { get; set; }
        public long? BeContMorahist150d12mBan { get; set; }
        public long? BeContMorahist120d24mCom { get; set; }
        public long? BeContMorahist30d36mCom0 { get; set; }
        public long? BeRefMoraactualTelco302000 { get; set; }
        public long? BeContMorahist30d6mTar0 { get; set; }
        public long? BeContMorahist30d6mTar1000 { get; set; }
        public long? BeContMorahist120d12mTar { get; set; }
        public long? BeSaldomoraact60Com500 { get; set; }
        public long? BeRefMoraactual30Ban0 { get; set; }
        public long? BeSaldomoraact30Com2000 { get; set; }
        public long? BeSaldomoraact60Telco1500 { get; set; }
        public long? BeRefMoraactual120Imf { get; set; }
        public long? BeContMorahist150d36mTar { get; set; }
        public long? BeContMorahist60d24mTelco0 { get; set; }
        public long? BeContCalifCfm24mBan { get; set; }
        public long? BeContMorahist30d24mTar1000 { get; set; }
        public long? BeContCalifIii12mTar { get; set; }
        public long? BeRefjudicialCom { get; set; }
        public long? BeSaldomoraact60Com1000 { get; set; }
        public long? BeContMorahist150d24mImf { get; set; }
        public long? BeContMorahist90d36mTelco { get; set; }
        public long? BeSaldoMoraact120Tar { get; set; }
        public long? BeContMorahist120d6mImf { get; set; }
        public long? BeRefMoraactual180Ban { get; set; }
        public long? BeContCalifV24mBan { get; set; }
        public double? BeSaldomoraact120Ban { get; set; }
        public long? BeContSaldovencBan36m { get; set; }
        public long? BeSaldomoraact60Imf500 { get; set; }
        public long? BeRefMoraactualTelco60500 { get; set; }
        public long? BeRefMoraactualTelco120 { get; set; }
        public long? BeContMorahist180d36mBan { get; set; }
        public long? BeContMorahist120d36mCom { get; set; }
        public long? BeSaldomoraact30Imf1000 { get; set; }
        public long? BeRefMoraactual120Tar { get; set; }
        public long? BeContMorahist30d12mCom1000 { get; set; }
        public long? BeContMorahist150d36mCom { get; set; }
        public long? BeContCalifI24mTar { get; set; }
        public double? BeSaldomoraact30Ban1000 { get; set; }
        public long? BeSaldomoraact30Telco500 { get; set; }
        public long? BeSaldomoraact30Com500 { get; set; }
        public long? BeSaldomoraact150Com { get; set; }
        public long? BeContMorahist30d36mTar0 { get; set; }
        public long? BeContMorahist90d12mCom { get; set; }
        public long? BeContMorahist60d36mTar0 { get; set; }
        public long? BeContMorahist180d24mBan { get; set; }
        public long? BeRefMoraactual60Imf0 { get; set; }
        public long? BeContMorahist60d6mBan1000 { get; set; }
        public long? BeContCalifI12mTar { get; set; }
        public long? BeRefMoraactual30Com500 { get; set; }
        public long? BeContMorahist30d36mImf1000 { get; set; }
        public long? BeContMorahist60d36mImf0 { get; set; }
        public long? BeSaldomoraact150Telco { get; set; }
        public long? BeContMorahist150d12mImf { get; set; }
        public long? BeContMorahist150d6mTelco { get; set; }
        public long? BeContCalifV36mTar { get; set; }
        public long? BeContCalifV12mBan { get; set; }
        public double? BeSaldomoraact30Ban2000 { get; set; }
        public long? BeSaldoMoraact90Tar { get; set; }
        public long? BeContMorahist30d36mImf0 { get; set; }
        public long? BeRefMoraactual60Com1000 { get; set; }
        public long? BeContCalifCfm36mBan { get; set; }
        public long? BeRefMoraactual30Com2000 { get; set; }
        public long? BeRefMoraactual60Com0 { get; set; }
        public long? BeContMorahist60d24mTelco1000 { get; set; }
        public double? BeSaldocastActualBan { get; set; }
        public long? BeContMorahist90d12mTar { get; set; }
        public long? BeContMorahist60d24mCom1000 { get; set; }
        public long? BeContMorahist120d24mTelco { get; set; }
        public long? BeSaldoMoraact30dTar0 { get; set; }
        public long? BeContMorahist120d12mImf { get; set; }
        public long? BeContMorahist150d24mBan { get; set; }
        public long? BeContMorahist150d24mTelco { get; set; }
        public long? BeContMorahist60d24mBan0 { get; set; }
        public long? BeRefMoraactualTelco150 { get; set; }
        public long? BeSaldomoraact30Com1000 { get; set; }
        public long? BeContMorahist30d24mBan0 { get; set; }
        public double? BeSaldomoraact60Ban1000 { get; set; }
        public long? BeRefMoraactualTelco600 { get; set; }
        public long? BeSaldomoraact60Telco2000 { get; set; }
        public long? BeContMorahist60d12mBan1000 { get; set; }
        public long? BeContMorahist120d6mBan { get; set; }
        public long? BeSaldomoraact30Imf500 { get; set; }
        public long? BeSaldomoraact120Imf { get; set; }
        public long? BeSaldomoraact150Imf { get; set; }
        public long? BeContMorahist30d24mBan1000 { get; set; }
        public long? BeRefMoraactual30Imf1000 { get; set; }
        public long? BeContMorahist180d24mTelco { get; set; }
        public double? BeSaldomoraact30Ban0 { get; set; }
        public long? BeContSaldocastBan36m { get; set; }
        public long? BeRefMoraactual60Com500 { get; set; }
        public long? BeSaldomoraact30Telco2000 { get; set; }
        public long? BeRefMoraactual60Tar1500 { get; set; }
        public long? BeContCalifIi36mBan { get; set; }
        public long? BeRefMoraactual30Ban500 { get; set; }
        public long? BeContCalifIii12mBan { get; set; }
        public long? BeContMorahist30d24mTar0 { get; set; }
        public long? BeRefMoraactual30Com1500 { get; set; }
        public long? BeRefMoraactualTelco30500 { get; set; }
        public long? BeContMorahist180d24mImf { get; set; }
        public long? BeContMorahist30d6mCom1000 { get; set; }
        public long? BeContMorahist150d12mCom { get; set; }
        public long? BeSaldoMoraact180Tar { get; set; }
        public long? BeRefMoraactual30Ban2000 { get; set; }
        public long? BeContCalifIv24mTar { get; set; }
        public long? BeContMorahist180d12mBan { get; set; }
        public long? BeContMorahist150d6mImf { get; set; }
        public long? BeRefMoraactual150Com { get; set; }
        public long? BeContMorahist90d36mCom { get; set; }
        public long? BeSaldomoraact60Telco500 { get; set; }
        public long? BeContMorahist120d12mBan { get; set; }
        public long? BeSaldomoraact60Com0 { get; set; }
        public long? BeExistedataCli { get; set; }
        public long? BeContMorahist60d36mImf1000 { get; set; }
        public long? BeRefMoraactual120Ban { get; set; }
        public long? BeRefMoraactualTelco301500 { get; set; }
        public double? BeSaldomoraact150Ban { get; set; }
        public long? BeContMorahist60d36mTelco0 { get; set; }
        public long? BeRefMoraactual150Tar { get; set; }
        public long? BeRefMoraactual60Ban1000 { get; set; }
        public long? BeContCalifIi12mTar { get; set; }
        public long? BeContMorahist150d12mTar { get; set; }
        public long? BeContMorahist30d36mTar1000 { get; set; }
        public long? BeContMorahist60d12mCom0 { get; set; }
        public long? BeContMorahist150d36mTelco { get; set; }
        public long? BeRefMoraactual60Ban500 { get; set; }
        public long? BeContMorahist150d6mTar { get; set; }
        public long? BeRefMoraactualTelco601500 { get; set; }
        public long? BeContMorahist150d36mBan { get; set; }
        public long? BeSaldomoraact120Com { get; set; }
        public long? BeContMorahist30d6mImf1000 { get; set; }
        public long? BeContMorahist30d12mBan0 { get; set; }
        public long? BeContMorahist30d6mCom0 { get; set; }
        public long? BeRefMoraactual60Imf500 { get; set; }
        public long? BeRefMoraactual60Com2000 { get; set; }
        public long? BeContMorahist90d36mTar { get; set; }
        public long? BeContMorahist60d12mImf0 { get; set; }
        public long? BeContMorahist60d36mCom1000 { get; set; }
        public long? BeRefMoraactual90Com { get; set; }
        public long? BeSaldoMoraact30dTar1000 { get; set; }
        public long? BeContMorahist60d6mCom1000 { get; set; }
        public long? BeContMorahist120d24mImf { get; set; }
        public long? BeContCalifIii24mTar { get; set; }
        public long? BeContMorahist120d6mTar { get; set; }
        public long? BeRefMoraactual30Imf500 { get; set; }
        public long? BeContMorahist180d24mCom { get; set; }
        public double? BeSaldomoraact60Ban2000 { get; set; }
        public long? BeSaldomoraact30Imf2000 { get; set; }
        public long? BeContMorahist150d6mCom { get; set; }
        public long? BeContMorahist120d24mTar { get; set; }
        public long? BeContMorahist90d6mTelco { get; set; }
        public long? BeContCalifI12mBan { get; set; }
        public long? BeContMorahist60d12mTar0 { get; set; }
        public long? BeContMorahist180d6mTelco { get; set; }
        public long? BeContMorahist60d36mTelco1000 { get; set; }
        public long? BeRefMoraactual30Com0 { get; set; }
        public long? BeRefMoraactual90Tar { get; set; }
        public long? BeSaldomoraact30Telco1000 { get; set; }
        public long? BeContMorahist120d6mCom { get; set; }
        public long? BeContMorahist60d6mBan0 { get; set; }
        public long? BeContMorahist30d6mImf0 { get; set; }
        public long? BeSaldoMoraact60dTar1500 { get; set; }
        public long? BeSaldomoraact90Com { get; set; }
        public long? BeContMorahist60d6mImf1000 { get; set; }
        public long? BeRefMoraactual30Ban1000 { get; set; }
        public long? BeContCalifV12mTar { get; set; }
        public long? BeRefMoraactual30Imf0 { get; set; }
        public long? BeContCalifCfm36mTar { get; set; }
        public long? BeContMorahist30d36mTelco1000 { get; set; }
        public long? BeSaldomoraact60Telco0 { get; set; }
        public double? BeSaldomoraact30Ban1500 { get; set; }
        public long? BeContMorahist150d36mImf { get; set; }
        public long? BeContCalifV36mBan { get; set; }
        public long? BeContMorahist60d36mTar1000 { get; set; }
        public long? BeContCalifIv24mBan { get; set; }
        public long? BeSaldomoraact60Imf1000 { get; set; }
        public long? BeContMorahist180d24mTar { get; set; }
        public long? Candidateinfoid { get; set; }
        public long Calculatesid { get; set; }
    }
}
