using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebAPI_IDH.Models
{
    public partial class Equifax
    {
        public long Id { get; set; }
        public string MoDomicilioZonariesgoDesc { get; set; }
        public decimal? MoDomicilioZonariesgoAcc { get; set; }
        public decimal? MoEndeudamientoActual { get; set; }
        public decimal? MoEndeudamientoSalida { get; set; }
        public decimal? MoTipoViviendaAcc { get; set; }
        public string MoTipoViviendaDes { get; set; }
        public decimal? MoAntiguedadDomicilioActual { get; set; }
        public decimal? MoEdad { get; set; }
        public string MoNombreCliente { get; set; }
        public string MoProfesionDes { get; set; }
        public decimal? MoProfesionAcc { get; set; }
        public string MoActividadeconomicaDes { get; set; }
        public decimal? MoActividadeconomicaAcc { get; set; }
        public decimal? MoNacionalidadAcc { get; set; }
        public string MoNacionalidadDes { get; set; }
        public decimal? MoAntiguedadLaboral { get; set; }
        public decimal? MoTipoPersona { get; set; }
        public decimal? MoEgreso { get; set; }
        public string MoEstadoCivilDes { get; set; }
        public decimal? MoEstadoCivilAcc { get; set; }
        public decimal? MoCuotaIngreso { get; set; }
        public decimal? MoCuota { get; set; }
        public decimal? MoIngreso { get; set; }
        public decimal? Entidad { get; set; }
        public decimal? BeExistedataCli { get; set; }
        public decimal? BeScore { get; set; }
        public decimal? BePromScore { get; set; }
        public decimal? BeCalificacionActual { get; set; }
        public decimal? BeSaldocastActualBan { get; set; }
        public decimal? BeSaldovencBan { get; set; }
        public decimal? BeSaldomoraact30Ban0 { get; set; }
        public decimal? BeSaldomoraact30Ban500 { get; set; }
        public decimal? BeSaldomoraact30Ban1000 { get; set; }
        public decimal? BeSaldomoraact30Ban1500 { get; set; }
        public decimal? BeSaldomoraact30Ban2000 { get; set; }
        public decimal? BeSaldomoraact60Ban0 { get; set; }
        public decimal? BeSaldomoraact60Ban500 { get; set; }
        public decimal? BeSaldomoraact60Ban1000 { get; set; }
        public decimal? BeSaldomoraact60Ban1500 { get; set; }
        public decimal? BeSaldomoraact60Ban2000 { get; set; }
        public decimal? BeSaldomoraact90Ban { get; set; }
        public decimal? BeSaldomoraact120Ban { get; set; }
        public decimal? BeSaldomoraact150Ban { get; set; }
        public decimal? BeSaldomoraact180Ban { get; set; }
        public decimal? BeRefMoraactual30Ban0 { get; set; }
        public decimal? BeRefMoraactual30Ban500 { get; set; }
        public decimal? BeRefMoraactual30Ban1000 { get; set; }
        public decimal? BeRefMoraactual30Ban1500 { get; set; }
        public decimal? BeRefMoraactual30Ban2000 { get; set; }
        public decimal? BeRefMoraactual60Ban0 { get; set; }
        public decimal? BeRefMoraactual60Ban500 { get; set; }
        public decimal? BeRefMoraactual60Ban1000 { get; set; }
        public decimal? BeRefMoraactual60Ban1500 { get; set; }
        public decimal? BeRefMoraactual60Ban2000 { get; set; }
        public decimal? BeRefMoraactual90Ban { get; set; }
        public decimal? BeRefMoraactual120Ban { get; set; }
        public decimal? BeRefMoraactual150Ban { get; set; }
        public decimal? BeRefMoraactual180Ban { get; set; }
        public decimal? BeContSaldocastBan36m { get; set; }
        public decimal? BeContSaldovencBan36m { get; set; }
        public decimal? BeContMorahist30d6mBan0 { get; set; }
        public decimal? BeContMorahist30d6mBan1000 { get; set; }
        public decimal? BeContMorahist30d12mBan0 { get; set; }
        public decimal? BeContMorahist30d12mBan1000 { get; set; }
        public decimal? BeContMorahist30d24mBan0 { get; set; }
        public decimal? BeContMorahist30d24mBan1000 { get; set; }
        public decimal? BeContMorahist30d36mBan0 { get; set; }
        public decimal? BeContMorahist30d36mBan1000 { get; set; }
        public decimal? BeContMorahist60d6mBan0 { get; set; }
        public decimal? BeContMorahist60d6mBan1000 { get; set; }
        public decimal? BeContMorahist60d12mBan0 { get; set; }
        public decimal? BeContMorahist60d12mBan1000 { get; set; }
        public decimal? BeContMorahist60d24mBan0 { get; set; }
        public decimal? BeContMorahist60d24mBan1000 { get; set; }
        public decimal? BeContMorahist60d36mBan0 { get; set; }
        public decimal? BeContMorahist60d36mBan1000 { get; set; }
        public decimal? BeContMorahist90d6mBan { get; set; }
        public decimal? BeContMorahist90d12mBan { get; set; }
        public decimal? BeContMorahist90d24mBan { get; set; }
        public decimal? BeContMorahist90d36mBan { get; set; }
        public decimal? BeContMorahist120d6mBan { get; set; }
        public decimal? BeContMorahist120d12mBan { get; set; }
        public decimal? BeContMorahist120d24mBan { get; set; }
        public decimal? BeContMorahist120d36mBan { get; set; }
        public decimal? BeContMorahist150d6mBan { get; set; }
        public decimal? BeContMorahist150d12mBan { get; set; }
        public decimal? BeContMorahist150d24mBan { get; set; }
        public decimal? BeContMorahist150d36mBan { get; set; }
        public decimal? BeContMorahist180d6mBan { get; set; }
        public decimal? BeContMorahist180d12mBan { get; set; }
        public decimal? BeContMorahist180d24mBan { get; set; }
        public decimal? BeContMorahist180d36mBan { get; set; }
        public decimal? BePeorCalif12mBan { get; set; }
        public decimal? BeContCalifCfm12mBan { get; set; }
        public decimal? BeContCalifV12mBan { get; set; }
        public decimal? BeContCalifIv12mBan { get; set; }
        public decimal? BeContCalifIii12mBan { get; set; }
        public decimal? BeContCalifIi12mBan { get; set; }
        public decimal? BeContCalifI12mBan { get; set; }
        public decimal? BePeorCalif24mBan { get; set; }
        public decimal? BeContCalifCfm24mBan { get; set; }
        public decimal? BeContCalifV24mBan { get; set; }
        public decimal? BeContCalifIv24mBan { get; set; }
        public decimal? BeContCalifIii24mBan { get; set; }
        public decimal? BeContCalifIi24mBan { get; set; }
        public decimal? BeContCalifI24mBan { get; set; }
        public decimal? BePeorCalif36mBan { get; set; }
        public decimal? BeContCalifCfm36mBan { get; set; }
        public decimal? BeContCalifV36mBan { get; set; }
        public decimal? BeContCalifIv36mBan { get; set; }
        public decimal? BeContCalifIii36mBan { get; set; }
        public decimal? BeContCalifIi36mBan { get; set; }
        public decimal? BeContCalifI36mBan { get; set; }
        public decimal? BeTarCalificacionActual { get; set; }
        public decimal? BeSaldoMoraact30dTar0 { get; set; }
        public decimal? BeSaldoMoraact30dTar500 { get; set; }
        public decimal? BeSaldoMoraact30dTar1000 { get; set; }
        public decimal? BeSaldoMoraact30dTar1500 { get; set; }
        public decimal? BeSaldoMoraact30dTar2000 { get; set; }
        public decimal? BeSaldoMoraact60dTar0 { get; set; }
        public decimal? BeSaldoMoraact60dTar500 { get; set; }
        public decimal? BeSaldoMoraact60dTar1000 { get; set; }
        public decimal? BeSaldoMoraact60dTar1500 { get; set; }
        public decimal? BeSaldoMoraact60dTar2000 { get; set; }
        public decimal? BeSaldoMoraact90Tar { get; set; }
        public decimal? BeSaldoMoraact120Tar { get; set; }
        public decimal? BeSaldoMoraact150Tar { get; set; }
        public decimal? BeSaldoMoraact180Tar { get; set; }
        public decimal? BeRefMoraactual30Tar0 { get; set; }
        public decimal? BeRefMoraactual30Tar500 { get; set; }
        public decimal? BeRefMoraactual30Tar1000 { get; set; }
        public decimal? BeRefMoraactual30Tar1500 { get; set; }
        public decimal? BeRefMoraactual30Tar2000 { get; set; }
        public decimal? BeRefMoraactual60Tar0 { get; set; }
        public decimal? BeRefMoraactual60Tar500 { get; set; }
        public decimal? BeRefMoraactual60Tar1000 { get; set; }
        public decimal? BeRefMoraactual60Tar1500 { get; set; }
        public decimal? BeRefMoraactual60Tar2000 { get; set; }
        public decimal? BeRefMoraactual90Tar { get; set; }
        public decimal? BeRefMoraactual120Tar { get; set; }
        public decimal? BeRefMoraactual150Tar { get; set; }
        public decimal? BeRefMoraactual180Tar { get; set; }
        public decimal? BeContSaldocastTar36m { get; set; }
        public decimal? BeContSaldovencTar36m { get; set; }
        public decimal? BeContMorahist30d6mTar0 { get; set; }
        public decimal? BeContMorahist30d6mTar1000 { get; set; }
        public decimal? BeContMorahist30d12mTar0 { get; set; }
        public decimal? BeContMorahist30d12mTar1000 { get; set; }
        public decimal? BeContMorahist30d24mTar0 { get; set; }
        public decimal? BeContMorahist30d24mTar1000 { get; set; }
        public decimal? BeContMorahist30d36mTar0 { get; set; }
        public decimal? BeContMorahist30d36mTar1000 { get; set; }
        public decimal? BeContMorahist60d6mTar0 { get; set; }
        public decimal? BeContMorahist60d6mTar1000 { get; set; }
        public decimal? BeContMorahist60d12mTar0 { get; set; }
        public decimal? BeContMorahist60d12mTar1000 { get; set; }
        public decimal? BeContMorahist60d24mTar0 { get; set; }
        public decimal? BeContMorahist60d24mTar1000 { get; set; }
        public decimal? BeContMorahist60d36mTar0 { get; set; }
        public decimal? BeContMorahist60d36mTar1000 { get; set; }
        public decimal? BeContMorahist90d6mTar { get; set; }
        public decimal? BeContMorahist90d12mTar { get; set; }
        public decimal? BeContMorahist90d24mTar { get; set; }
        public decimal? BeContMorahist90d36mTar { get; set; }
        public decimal? BeContMorahist120d6mTar { get; set; }
        public decimal? BeContMorahist120d12mTar { get; set; }
        public decimal? BeContMorahist120d24mTar { get; set; }
        public decimal? BeContMorahist120d36mTar { get; set; }
        public decimal? BeContMorahist150d6mTar { get; set; }
        public decimal? BeContMorahist150d12mTar { get; set; }
        public decimal? BeContMorahist150d24mTar { get; set; }
        public decimal? BeContMorahist150d36mTar { get; set; }
        public decimal? BeContMorahist180d6mTar { get; set; }
        public decimal? BeContMorahist180d12mTar { get; set; }
        public decimal? BeContMorahist180d24mTar { get; set; }
        public decimal? BeContMorahist180d36mTar { get; set; }
        public decimal? BePeorCalif12mTar { get; set; }
        public decimal? BeContCalifCfm12mTar { get; set; }
        public decimal? BeContCalifV12mTar { get; set; }
        public decimal? BeContCalifIv12mTar { get; set; }
        public decimal? BeContCalifIii12mTar { get; set; }
        public decimal? BeContCalifIi12mTar { get; set; }
        public decimal? BeContCalifI12mTar { get; set; }
        public decimal? BePeorCalif24mTar { get; set; }
        public decimal? BeContCalifCfm24mTar { get; set; }
        public decimal? BeContCalifV24mTar { get; set; }
        public decimal? BeContCalifIv24mTar { get; set; }
        public decimal? BeContCalifIii24mTar { get; set; }
        public decimal? BeContCalifIi24mTar { get; set; }
        public decimal? BeContCalifI24mTar { get; set; }
        public decimal? BePeorCalif36mTar { get; set; }
        public decimal? BeContCalifCfm36mTar { get; set; }
        public decimal? BeContCalifV36mTar { get; set; }
        public decimal? BeContCalifIv36mTar { get; set; }
        public decimal? BeContCalifIii36mTar { get; set; }
        public decimal? BeContCalifIi36mTar { get; set; }
        public decimal? BeContCalifI36mTar { get; set; }
        public decimal? BeRefMoraactualCobroadminCom { get; set; }
        public decimal? BeRefjudicialCom { get; set; }
        public decimal? BeSaldomoraact30Com0 { get; set; }
        public decimal? BeSaldomoraact30Com500 { get; set; }
        public decimal? BeSaldomoraact30Com1000 { get; set; }
        public decimal? BeSaldomoraact30Com1500 { get; set; }
        public decimal? BeSaldomoraact30Com2000 { get; set; }
        public decimal? BeSaldomoraact60Com0 { get; set; }
        public decimal? BeSaldomoraact60Com500 { get; set; }
        public decimal? BeSaldomoraact60Com1000 { get; set; }
        public decimal? BeSaldomoraact60Com1500 { get; set; }
        public decimal? BeSaldomoraact60Com2000 { get; set; }
        public decimal? BeSaldomoraact90Com { get; set; }
        public decimal? BeSaldomoraact120Com { get; set; }
        public decimal? BeSaldomoraact150Com { get; set; }
        public decimal? BeSaldomoraact180Com { get; set; }
        public decimal? BeRefMoraactual30Com0 { get; set; }
        public decimal? BeRefMoraactual30Com500 { get; set; }
        public decimal? BeRefMoraactual30Com1000 { get; set; }
        public decimal? BeRefMoraactual30Com1500 { get; set; }
        public decimal? BeRefMoraactual30Com2000 { get; set; }
        public decimal? BeRefMoraactual60Com0 { get; set; }
        public decimal? BeRefMoraactual60Com500 { get; set; }
        public decimal? BeRefMoraactual60Com1000 { get; set; }
        public decimal? BeRefMoraactual60Com1500 { get; set; }
        public decimal? BeRefMoraactual60Com2000 { get; set; }
        public decimal? BeRefMoraactual90Com { get; set; }
        public decimal? BeRefMoraactual120Com { get; set; }
        public decimal? BeRefMoraactual150Com { get; set; }
        public decimal? BeRefMoraactual180Com { get; set; }
        public decimal? BeContMorahist30d6mCom0 { get; set; }
        public decimal? BeContMorahist30d6mCom1000 { get; set; }
        public decimal? BeContMorahist30d12mCom0 { get; set; }
        public decimal? BeContMorahist30d12mCom1000 { get; set; }
        public decimal? BeContMorahist30d24mCom0 { get; set; }
        public decimal? BeContMorahist30d24mCom1000 { get; set; }
        public decimal? BeContMorahist30d36mCom0 { get; set; }
        public decimal? BeContMorahist30d36mCom1000 { get; set; }
        public decimal? BeContMorahist60d6mCom0 { get; set; }
        public decimal? BeContMorahist60d6mCom1000 { get; set; }
        public decimal? BeContMorahist60d12mCom0 { get; set; }
        public decimal? BeContMorahist60d12mCom1000 { get; set; }
        public decimal? BeContMorahist60d24mCom0 { get; set; }
        public decimal? BeContMorahist60d24mCom1000 { get; set; }
        public decimal? BeContMorahist60d36mCom0 { get; set; }
        public decimal? BeContMorahist60d36mCom1000 { get; set; }
        public decimal? BeContMorahist90d6mCom { get; set; }
        public decimal? BeContMorahist90d12mCom { get; set; }
        public decimal? BeContMorahist90d24mCom { get; set; }
        public decimal? BeContMorahist90d36mCom { get; set; }
        public decimal? BeContMorahist120d6mCom { get; set; }
        public decimal? BeContMorahist120d12mCom { get; set; }
        public decimal? BeContMorahist120d24mCom { get; set; }
        public decimal? BeContMorahist120d36mCom { get; set; }
        public decimal? BeContMorahist150d6mCom { get; set; }
        public decimal? BeContMorahist150d12mCom { get; set; }
        public decimal? BeContMorahist150d24mCom { get; set; }
        public decimal? BeContMorahist150d36mCom { get; set; }
        public decimal? BeContMorahist180d6mCom { get; set; }
        public decimal? BeContMorahist180d12mCom { get; set; }
        public decimal? BeContMorahist180d24mCom { get; set; }
        public decimal? BeContMorahist180d36mCom { get; set; }
        public decimal? BeRefMoraactualCobroadminImf { get; set; }
        public decimal? BeSaldomoraact30Imf0 { get; set; }
        public decimal? BeSaldomoraact30Imf500 { get; set; }
        public decimal? BeSaldomoraact30Imf1000 { get; set; }
        public decimal? BeSaldomoraact30Imf1500 { get; set; }
        public decimal? BeSaldomoraact30Imf2000 { get; set; }
        public decimal? BeSaldomoraact60Imf0 { get; set; }
        public decimal? BeSaldomoraact60Imf500 { get; set; }
        public decimal? BeSaldomoraact60Imf1000 { get; set; }
        public decimal? BeSaldomoraact60Imf1500 { get; set; }
        public decimal? BeSaldomoraact60Imf2000 { get; set; }
        public decimal? BeSaldomoraact90Imf { get; set; }
        public decimal? BeSaldomoraact120Imf { get; set; }
        public decimal? BeSaldomoraact150Imf { get; set; }
        public decimal? BeSaldomoraact180Imf { get; set; }
        public decimal? BeRefMoraactual30Imf0 { get; set; }
        public decimal? BeRefMoraactual30Imf500 { get; set; }
        public decimal? BeRefMoraactual30Imf1000 { get; set; }
        public decimal? BeRefMoraactual30Imf1500 { get; set; }
        public decimal? BeRefMoraactual30Imf2000 { get; set; }
        public decimal? BeRefMoraactual60Imf0 { get; set; }
        public decimal? BeRefMoraactual60Imf500 { get; set; }
        public decimal? BeRefMoraactual60Imf1000 { get; set; }
        public decimal? BeRefMoraactual60Imf1500 { get; set; }
        public decimal? BeRefMoraactual60Imf2000 { get; set; }
        public decimal? BeRefMoraactual90Imf { get; set; }
        public decimal? BeRefMoraactual120Imf { get; set; }
        public decimal? BeRefMoraactual150Imf { get; set; }
        public decimal? BeRefMoraactual180Imf { get; set; }
        public decimal? BeContMorahist30d6mImf0 { get; set; }
        public decimal? BeContMorahist30d6mImf1000 { get; set; }
        public decimal? BeContMorahist30d12mImf0 { get; set; }
        public decimal? BeContMorahist30d12mImf1000 { get; set; }
        public decimal? BeContMorahist30d24mImf0 { get; set; }
        public decimal? BeContMorahist30d24mImf1000 { get; set; }
        public decimal? BeContMorahist30d36mImf0 { get; set; }
        public decimal? BeContMorahist30d36mImf1000 { get; set; }
        public decimal? BeContMorahist60d6mImf0 { get; set; }
        public decimal? BeContMorahist60d6mImf1000 { get; set; }
        public decimal? BeContMorahist60d12mImf0 { get; set; }
        public decimal? BeContMorahist60d12mImf1000 { get; set; }
        public decimal? BeContMorahist60d24mImf0 { get; set; }
        public decimal? BeContMorahist60d24mImf1000 { get; set; }
        public decimal? BeContMorahist60d36mImf0 { get; set; }
        public decimal? BeContMorahist60d36mImf1000 { get; set; }
        public decimal? BeContMorahist90d6mImf { get; set; }
        public decimal? BeContMorahist90d12mImf { get; set; }
        public decimal? BeContMorahist90d24mImf { get; set; }
        public decimal? BeContMorahist90d36mImf { get; set; }
        public decimal? BeContMorahist120d6mImf { get; set; }
        public decimal? BeContMorahist120d12mImf { get; set; }
        public decimal? BeContMorahist120d24mImf { get; set; }
        public decimal? BeContMorahist120d36mImf { get; set; }
        public decimal? BeContMorahist150d6mImf { get; set; }
        public decimal? BeContMorahist150d12mImf { get; set; }
        public decimal? BeContMorahist150d24mImf { get; set; }
        public decimal? BeContMorahist150d36mImf { get; set; }
        public decimal? BeContMorahist180d6mImf { get; set; }
        public decimal? BeContMorahist180d12mImf { get; set; }
        public decimal? BeContMorahist180d24mImf { get; set; }
        public decimal? BeContMorahist180d36mImf { get; set; }
        public decimal? BeRefMoraactualCobroadminTelco { get; set; }
        public decimal? BeSaldomoraact30Telco0 { get; set; }
        public decimal? BeSaldomoraact30Telco500 { get; set; }
        public decimal? BeSaldomoraact30Telco1000 { get; set; }
        public decimal? BeSaldomoraact30Telco1500 { get; set; }
        public decimal? BeSaldomoraact30Telco2000 { get; set; }
        public decimal? BeSaldomoraact60Telco0 { get; set; }
        public decimal? BeSaldomoraact60Telco500 { get; set; }
        public decimal? BeSaldomoraact60Telco1000 { get; set; }
        public decimal? BeSaldomoraact60Telco1500 { get; set; }
        public decimal? BeSaldomoraact60Telco2000 { get; set; }
        public decimal? BeSaldomoraact90Telco { get; set; }
        public decimal? BeSaldomoraact120Telco { get; set; }
        public decimal? BeSaldomoraact150Telco { get; set; }
        public decimal? BeSaldomoraact180Telco { get; set; }
        public decimal? BeRefMoraactualTelco300 { get; set; }
        public decimal? BeRefMoraactualTelco30500 { get; set; }
        public decimal? BeRefMoraactualTelco301000 { get; set; }
        public decimal? BeRefMoraactualTelco301500 { get; set; }
        public decimal? BeRefMoraactualTelco302000 { get; set; }
        public decimal? BeRefMoraactualTelco600 { get; set; }
        public decimal? BeRefMoraactualTelco60500 { get; set; }
        public decimal? BeRefMoraactualTelco601000 { get; set; }
        public decimal? BeRefMoraactualTelco601500 { get; set; }
        public decimal? BeRefMoraactualTelco602000 { get; set; }
        public decimal? BeRefMoraactualTelco90 { get; set; }
        public decimal? BeRefMoraactualTelco120 { get; set; }
        public decimal? BeRefMoraactualTelco150 { get; set; }
        public decimal? BeRefMoraactualTelco180 { get; set; }
        public decimal? BeContMorahist30d6mTelco0 { get; set; }
        public decimal? BeContMorahist30d6mTelco1000 { get; set; }
        public decimal? BeContMorahist30d12mTelco0 { get; set; }
        public decimal? BeContMorahist30d12mTelco1000 { get; set; }
        public decimal? BeContMorahist30d24mTelco0 { get; set; }
        public decimal? BeContMorahist30d24mTelco1000 { get; set; }
        public decimal? BeContMorahist30d36mTelco0 { get; set; }
        public decimal? BeContMorahist30d36mTelco1000 { get; set; }
        public decimal? BeContMorahist60d6mTelco0 { get; set; }
        public decimal? BeContMorahist60d6mTelco1000 { get; set; }
        public decimal? BeContMorahist60d12mTelco0 { get; set; }
        public decimal? BeContMorahist60d12mTelco1000 { get; set; }
        public decimal? BeContMorahist60d24mTelco0 { get; set; }
        public decimal? BeContMorahist60d24mTelco1000 { get; set; }
        public decimal? BeContMorahist60d36mTelco0 { get; set; }
        public decimal? BeContMorahist60d36mTelco1000 { get; set; }
        public decimal? BeContMorahist90d6mTelco { get; set; }
        public decimal? BeContMorahist90d12mTelco { get; set; }
        public decimal? BeContMorahist90d24mTelco { get; set; }
        public decimal? BeContMorahist90d36mTelco { get; set; }
        public decimal? BeContMorahist120d6mTelco { get; set; }
        public decimal? BeContMorahist120d12mTelco { get; set; }
        public decimal? BeContMorahist120d24mTelco { get; set; }
        public decimal? BeContMorahist120d36mTelco { get; set; }
        public decimal? BeContMorahist150d6mTelco { get; set; }
        public decimal? BeContMorahist150d12mTelco { get; set; }
        public decimal? BeContMorahist150d24mTelco { get; set; }
        public decimal? BeContMorahist150d36mTelco { get; set; }
        public decimal? BeContMorahist180d6mTelco { get; set; }
        public decimal? BeContMorahist180d12mTelco { get; set; }
        public decimal? BeContMorahist180d24mTelco { get; set; }
        public decimal? BeContMorahist180d36mTelco { get; set; }
        public string FchConsulta { get; set; }
    }
}
