using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebAPI_IDH.Models
{
    public partial class SldoPmo
    {
        public string FchCierre { get; set; }
        public string Prestamo { get; set; }
        public string Cliente { get; set; }
        public decimal Gestor { get; set; }
        public string FchApro { get; set; }
        public string FchAper { get; set; }
        public string FchVenc { get; set; }
        public string FchUcalc { get; set; }
        public string FchUcap { get; set; }
        public string Fch1erpgo { get; set; }
        public string ProxPgo { get; set; }
        public string Cptlizar { get; set; }
        public string Cobramora { get; set; }
        public string Cobraint { get; set; }
        public string FchUe { get; set; }
        public string FchUmvo { get; set; }
        public string FchUpgo { get; set; }
        public string FchUin { get; set; }
        public string FchUmora { get; set; }
        public decimal Cuotas { get; set; }
        public decimal VlcuotaAnterior { get; set; }
        public decimal Vlcuota { get; set; }
        public string Tieneaval { get; set; }
        public string Tpgarantia { get; set; }
        public string DescTpgarantia { get; set; }
        public decimal TasaAnterior { get; set; }
        public string FchUChgTasa { get; set; }
        public decimal Tasa { get; set; }
        public decimal TasaMora { get; set; }
        public decimal Tpobligacion { get; set; }
        public string DescTpobligacion { get; set; }
        public decimal Tpcredito { get; set; }
        public string DescTpcredito { get; set; }
        public string CtaCapit1 { get; set; }
        public string Destino { get; set; }
        public string DescDest { get; set; }
        public decimal Frec2 { get; set; }
        public decimal Tipo { get; set; }
        public decimal Formapgo { get; set; }
        public string DescFormapgo { get; set; }
        public string Clase { get; set; }
        public string DescClase { get; set; }
        public decimal Oficial { get; set; }
        public decimal Estatus { get; set; }
        public string DescEstat { get; set; }
        public string Prefijo { get; set; }
        public decimal Frec { get; set; }
        public decimal Monto { get; set; }
        public decimal Capital { get; set; }
        public decimal SaldoAct { get; set; }
        public decimal SaldoActant { get; set; }
        public decimal SldVarios { get; set; }
        public decimal CapVenc { get; set; }
        public decimal CualVenc { get; set; }
        public decimal CuoVenc { get; set; }
        public decimal Diasmora { get; set; }
        public decimal CuoPags { get; set; }
        public decimal IntAcum { get; set; }
        public decimal IntAno { get; set; }
        public decimal IntPend { get; set; }
        public decimal IntVenc { get; set; }
        public decimal IntCap { get; set; }
        public decimal IntMesant { get; set; }
        public decimal IntPendant { get; set; }
        public decimal IntSuspenso { get; set; }
        public decimal IntPgdo { get; set; }
        public decimal IntMora { get; set; }
        public decimal IntMorames { get; set; }
        public decimal IntMoradia { get; set; }
        public decimal IntDia { get; set; }
        public decimal IntAyer { get; set; }
        public decimal IntMes { get; set; }
        public decimal IntProme { get; set; }
        public decimal Claseseg { get; set; }
        public decimal Estatusseg { get; set; }
        public string Fch1erseg { get; set; }
        public string FchVseg { get; set; }
        public string ProxSegu { get; set; }
        public string SeguPda { get; set; }
        public decimal SaldoSeg { get; set; }
        public decimal TotSeg1 { get; set; }
        public decimal PrimaSeg1 { get; set; }
        public decimal LmtSeg1 { get; set; }
        public decimal Seguro1 { get; set; }
        public decimal SaldoSg1 { get; set; }
        public decimal TotSeg2 { get; set; }
        public decimal PrimaSeg2 { get; set; }
        public decimal LmtSeg2 { get; set; }
        public decimal Seguro2 { get; set; }
        public decimal SaldoSg2 { get; set; }
        public decimal FrecSeg { get; set; }
        public decimal Degracia { get; set; }
        public string PlanRet { get; set; }
        public decimal Categoria { get; set; }
        public decimal CasillaPrevia { get; set; }
        public decimal CasillaOrig { get; set; }
        public decimal CasillaBch { get; set; }
        public decimal CasillaContab { get; set; }
        public string CatCnbsg { get; set; }
        public string DescCatCnbsg { get; set; }
        public string Numcatcnbsg { get; set; }
        public decimal Categoriag { get; set; }
        public decimal CasillaContabg { get; set; }
        public decimal CasillaPreviai { get; set; }
        public string CatCnbs { get; set; }
        public string DescCatCnbs { get; set; }
        public string Numcatcnbs { get; set; }
        public string CatCnbsprevia { get; set; }
        public decimal CategoriaPrevia { get; set; }
        public decimal Reserva { get; set; }
        public string Fondo { get; set; }
        public string DescFondo { get; set; }
        public string Programa { get; set; }
        public string DescPrg { get; set; }
        public string Codubi { get; set; }
        public string DescSuc { get; set; }
        public string Sucursal { get; set; }
        public string InstCnbs { get; set; }
        public decimal ManejaListado { get; set; }
        public string Solicitud { get; set; }
        public string ActivarGracia { get; set; }
        public decimal CambiarCatcnbs { get; set; }
        public string GrpCat { get; set; }
        public string NivelE { get; set; }
        public decimal TprenegociaDias { get; set; }
        public string Tprenegociacion { get; set; }
        public string DescTprenegociacion { get; set; }
        public string PrestamoRenegocia { get; set; }
        public decimal Moneda { get; set; }
        public string SiglaMoneda { get; set; }
        public string NombreMoneda { get; set; }
        public decimal Local1 { get; set; }
        public string Tpoperacion { get; set; }
        public string DescTpoperacion { get; set; }
        public decimal Engrupo { get; set; }
        public decimal Tipopmo { get; set; }
        public decimal IntFijo { get; set; }
        public decimal CargMra { get; set; }
        public decimal Crgmravenc { get; set; }
        public decimal IntSeguro { get; set; }
        public decimal MraCapit { get; set; }
        public decimal MraInts { get; set; }
        public decimal MraSeguro { get; set; }
        public decimal Categoriza { get; set; }
        public decimal Capitalizar { get; set; }
        public decimal Recoplan { get; set; }
        public string Tipodegracia { get; set; }
        public string CtaIntsuspenso { get; set; }
        public string CtaPtesuspenso { get; set; }
        public decimal ManejaIntsuspenso { get; set; }
        public decimal RptaCnbs { get; set; }
        public decimal CatCrrenegocia { get; set; }
        public decimal Modalidad { get; set; }
        public string DescModalidad { get; set; }
        public string CtaCapit { get; set; }
        public string CtaInters { get; set; }
        public string CtaMora { get; set; }
        public string CtaIngres { get; set; }
        public string CtaSeguro1 { get; set; }
        public string CtaSeguro2 { get; set; }
        public string CtaVarios { get; set; }
        public decimal Moramas365 { get; set; }
        public decimal Mora365 { get; set; }
        public decimal Mora180 { get; set; }
        public decimal Mora120 { get; set; }
        public decimal Mora90 { get; set; }
        public decimal Mora60 { get; set; }
        public decimal Mora30 { get; set; }
        public decimal Proycobro30 { get; set; }
        public decimal Proycobro60 { get; set; }
        public decimal Proycobro90 { get; set; }
        public decimal Proycobro120 { get; set; }
        public decimal Proycobro180 { get; set; }
        public decimal Proycobro365 { get; set; }
        public decimal Proycobromas365 { get; set; }
        public string EmpreSaf { get; set; }
        public string FchCreado { get; set; }
        public string CreadoPor { get; set; }
        public decimal Claseseg2 { get; set; }
        public string Subcatcnbs { get; set; }
        public decimal CatDeudor { get; set; }
        public string Subcatcnbsg { get; set; }
        public string GrpTpgarantia { get; set; }
        public string DescGrpTpgarantia { get; set; }
        public string Rangog { get; set; }
        public decimal IntNocrg { get; set; }
        public decimal VlcuotaReal { get; set; }
        public string DescGrpCat { get; set; }
        public decimal CostoAtotal { get; set; }
        public string FchCanc { get; set; }
        public string SubcatcnbsPrevia { get; set; }
        public string FchUabono { get; set; }
        public decimal CodAct { get; set; }
        public string DescAct { get; set; }
        public decimal CodMetodologia { get; set; }
        public string NombreMetodologia { get; set; }
        public decimal ProyCapmes0 { get; set; }
        public decimal Mes0Relativo { get; set; }
        public decimal ProyCapmes1 { get; set; }
        public decimal Mes1Relativo { get; set; }
        public decimal ProyCapmes2 { get; set; }
        public decimal Mes2Relativo { get; set; }
        public decimal ProyCapmes3 { get; set; }
        public decimal Mes3Relativo { get; set; }
        public decimal ProyCapmes4 { get; set; }
        public decimal Mes4Relativo { get; set; }
        public decimal ProyCapmes5 { get; set; }
        public decimal Mes5Relativo { get; set; }
        public decimal ProyCapmes6 { get; set; }
        public decimal Mes6Relativo { get; set; }
        public decimal ProyCapmes7 { get; set; }
        public decimal Mes7Relativo { get; set; }
        public decimal ProyCapmes8 { get; set; }
        public decimal Mes8Relativo { get; set; }
        public decimal ProyCapmes9 { get; set; }
        public decimal Mes9Relativo { get; set; }
        public decimal ProyCapmes10 { get; set; }
        public decimal Mes10Relativo { get; set; }
        public decimal ProyCapmes11 { get; set; }
        public decimal Mes11Relativo { get; set; }
        public decimal ProyCapmes12 { get; set; }
        public decimal Mes12Relativo { get; set; }
        public decimal ProyMcapmes12 { get; set; }
        public decimal ProyIntmes0 { get; set; }
        public decimal ProyIntmes1 { get; set; }
        public decimal ProyIntmes2 { get; set; }
        public decimal ProyIntmes3 { get; set; }
        public decimal ProyIntmes4 { get; set; }
        public decimal ProyIntmes5 { get; set; }
        public decimal ProyIntmes6 { get; set; }
        public decimal ProyIntmes7 { get; set; }
        public decimal ProyIntmes8 { get; set; }
        public decimal ProyIntmes9 { get; set; }
        public decimal ProyIntmes10 { get; set; }
        public decimal ProyIntmes11 { get; set; }
        public decimal ProyIntmes12 { get; set; }
        public decimal ProyMintmes12 { get; set; }
        public decimal Mora7 { get; set; }
        public decimal Mora15 { get; set; }
        public decimal Mora302 { get; set; }
        public decimal Tpcartera { get; set; }
        public decimal ClaseAnterior { get; set; }
        public string FchCastigo { get; set; }
        public decimal IdLineaCredito { get; set; }
        public decimal IntMesdiaant { get; set; }
        public decimal ClTasa { get; set; }
        public decimal ProyCap5anio { get; set; }
        public decimal ProyMcap5anio { get; set; }
        public decimal ProyInt5anio { get; set; }
        public decimal ProyMint5anio { get; set; }
        public decimal IntSuspensoant { get; set; }
    }
}
