using System;
using System.Collections.Generic;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace WebAPI_IDH.Models
{
    public partial class Transunion
    {
        public long Idconsulta { get; set; }
        public string Pais { get; set; }
        public string CodRepor { get; set; }
        public string Entidadconsultante { get; set; }
        public string Usuario { get; set; }
        public string Motivo { get; set; }
        public string Fchreporte { get; set; }
        public string Primerapellido { get; set; }
        public string Segundoapellido { get; set; }
        public string Primernombre { get; set; }
        public string Segundonombre { get; set; }
        public string Nombrecompleto { get; set; }
        public string Fchnacimiento { get; set; }
        public string Edad { get; set; }
        public string Genero { get; set; }
        public string Estadocivil { get; set; }
        public string Dependientes { get; set; }
        public string Cedula { get; set; }
        public string Estado { get; set; }
        public string Codtel { get; set; }
        public string Telefono { get; set; }
        public string Divisiongeografica1 { get; set; }
        public string Divisiongeografica2 { get; set; }
        public string Codtel2 { get; set; }
        public string Telefono2 { get; set; }
        public string Empresarepresentacion { get; set; }
        public string Identificacion { get; set; }
        public string Cargo { get; set; }
        public string Fchinscripcion { get; set; }
        public string Idsujeto { get; set; }
        public string Empresarepresen { get; set; }
        public string IdenteJuri { get; set; }
        public string CargoJuri { get; set; }
        public string Fchinscripcion1 { get; set; }
        public string IdsujetoJuri { get; set; }
        public string Tipocuenta { get; set; }
        public string Estado1 { get; set; }
        public string Cantidad { get; set; }
        public string Tipocuenta1 { get; set; }
        public string Estado2 { get; set; }
        public string Cantidad1 { get; set; }
        public string Tipocuenta2 { get; set; }
        public string Estado3 { get; set; }
        public string Cantidad2 { get; set; }
        public string Tipocuenta3 { get; set; }
        public string Estado4 { get; set; }
        public string Cantidad3 { get; set; }
        public string Tipocuenta4 { get; set; }
        public string Estado5 { get; set; }
        public string Cantidad4 { get; set; }
        public string Tipocuenta5 { get; set; }
        public string Estado6 { get; set; }
        public string Cantidad6 { get; set; }
        public string Tipocuenta6 { get; set; }
        public string Estado7 { get; set; }
        public string Cantidad7 { get; set; }
        public string Moneda1 { get; set; }
        public string Moneda2 { get; set; }
        public string Obligacion { get; set; }
        public string Entidadinformante { get; set; }
        public string TipoObliga { get; set; }
        public string GarantiaObliga { get; set; }
        public string NumeroObliga { get; set; }
        public string FchapertuaObliga { get; set; }
        public string FchvencObliga { get; set; }
        public string FchactualizacionObliga { get; set; }
        public string PeriodoPagoObliga { get; set; }
        public string ClasificacionComporta { get; set; }
        public string MonedaComporta { get; set; }
        public string EstadoComporta { get; set; }
        public string LimiteComporta { get; set; }
        public string SaldoactualComporta { get; set; }
        public string SaldomoraComporta { get; set; }
        public string CuotaComporta { get; set; }
        public string VectorhistoAnio { get; set; }
        public string VectorhistoAnio1 { get; set; }
        public string VectorhistoAnio2 { get; set; }
        public string VectorhistoAnio3 { get; set; }
        public string VectorhistoAnio4 { get; set; }
        public string VectorhistoAnio5 { get; set; }
        public string VectorhistoAnio6 { get; set; }
        public string VectorhistoAnio7 { get; set; }
        public string VectorhistoAnio8 { get; set; }
        public string VectorhistoAnio9 { get; set; }
        public string VectorhistoAnio10 { get; set; }
        public string VectorhistoAnio11 { get; set; }
        public string VectorhistoAnio12 { get; set; }
        public string VectorhistoAnio13 { get; set; }
        public string VectorhistoAnio14 { get; set; }
        public string VectorhistoAnio15 { get; set; }
        public string VectorhistoAnio16 { get; set; }
        public string VectorhistoAnio17 { get; set; }
        public string VectorhistoAnio18 { get; set; }
        public string VectorhistoAnio19 { get; set; }
        public string VectorhistoAnio20 { get; set; }
        public string VectorhistoAnio21 { get; set; }
        public string VectorhistoAnio22 { get; set; }
        public string VectorhistoAnio23 { get; set; }
        public string VectorhistoAnio24 { get; set; }
        public string VectorhistoMes { get; set; }
        public string VectorhistoMes1 { get; set; }
        public string VectorhistoMes2 { get; set; }
        public string VectorhistoMes3 { get; set; }
        public string VectorhistoMes4 { get; set; }
        public string VectorhistoMes5 { get; set; }
        public string VectorhistoMes6 { get; set; }
        public string VectorhistoMes7 { get; set; }
        public string VectorhistoMes8 { get; set; }
        public string VectorhistoMes9 { get; set; }
        public string VectorhistoMes10 { get; set; }
        public string VectorhistoMes11 { get; set; }
        public string VectorhistoMes12 { get; set; }
        public string VectorhistoMes13 { get; set; }
        public string VectorhistoMes14 { get; set; }
        public string VectorhistoMes15 { get; set; }
        public string VectorhistoMes16 { get; set; }
        public string VectorhistoMes17 { get; set; }
        public string VectorhistoMes18 { get; set; }
        public string VectorhistoMes19 { get; set; }
        public string VectorhistoMes20 { get; set; }
        public string VectorhistoMes21 { get; set; }
        public string VectorhistoMes22 { get; set; }
        public string VectorhistoMes23 { get; set; }
        public string VectorhistoMes24 { get; set; }
        public string Obligacion1 { get; set; }
        public string Entidadinformante1 { get; set; }
        public string TipoObliga1 { get; set; }
        public string GarantiaObliga1 { get; set; }
        public string NumeroObliga1 { get; set; }
        public string FchapertuaObliga1 { get; set; }
        public string FchvencObliga1 { get; set; }
        public string FchactualizacionObliga1 { get; set; }
        public string PeriodoPagoObliga1 { get; set; }
        public string ClasificacionComporta1 { get; set; }
        public string MonedaComporta1 { get; set; }
        public string EstadoComporta1 { get; set; }
        public string LimiteComporta1 { get; set; }
        public string SaldoactualComporta1 { get; set; }
        public string SaldomoraComporta1 { get; set; }
        public string CuotaComporta1 { get; set; }
        public string Vectorhisto1Anio { get; set; }
        public string Vectorhisto1Anio1 { get; set; }
        public string Vectorhisto1Anio2 { get; set; }
        public string Vectorhisto1Anio3 { get; set; }
        public string Vectorhisto1Anio4 { get; set; }
        public string Vectorhisto1Anio5 { get; set; }
        public string Vectorhisto1Anio6 { get; set; }
        public string Vectorhisto1Anio7 { get; set; }
        public string Vectorhisto1Anio8 { get; set; }
        public string Vectorhisto1Anio9 { get; set; }
        public string Vectorhisto1Anio10 { get; set; }
        public string Vectorhisto1Anio11 { get; set; }
        public string Vectorhisto1Anio12 { get; set; }
        public string Vectorhisto1Anio13 { get; set; }
        public string Vectorhisto1Anio14 { get; set; }
        public string Vectorhisto1Anio15 { get; set; }
        public string Vectorhisto1Anio16 { get; set; }
        public string Vectorhisto1Anio17 { get; set; }
        public string Vectorhisto1Anio18 { get; set; }
        public string Vectorhisto1Anio19 { get; set; }
        public string Vectorhisto1Anio20 { get; set; }
        public string Vectorhisto1Anio21 { get; set; }
        public string Vectorhisto1Anio22 { get; set; }
        public string Vectorhisto1Anio23 { get; set; }
        public string Vectorhisto1Anio24 { get; set; }
        public string Vectorhisto1Mes1 { get; set; }
        public string Vectorhisto1Mes2 { get; set; }
        public string Vectorhisto1Mes3 { get; set; }
        public string Vectorhisto1Mes4 { get; set; }
        public string Vectorhisto1Mes5 { get; set; }
        public string Vectorhisto1Mes6 { get; set; }
        public string Vectorhisto1Mes7 { get; set; }
        public string Vectorhisto1Mes8 { get; set; }
        public string Vectorhisto1Mes9 { get; set; }
        public string Vectorhisto1Mes10 { get; set; }
        public string Vectorhisto1Mes11 { get; set; }
        public string Vectorhisto1Mes12 { get; set; }
        public string Vectorhisto1Mes13 { get; set; }
        public string Vectorhisto1Mes14 { get; set; }
        public string Vectorhisto1Mes15 { get; set; }
        public string Vectorhisto1Mes16 { get; set; }
        public string Vectorhisto1Mes17 { get; set; }
        public string Vectorhisto1Mes18 { get; set; }
        public string Vectorhisto1Mes19 { get; set; }
        public string Vectorhisto1Mes20 { get; set; }
        public string Vectorhisto1Mes21 { get; set; }
        public string Vectorhisto1Mes22 { get; set; }
        public string Vectorhisto1Mes23 { get; set; }
        public string Vectorhisto1Mes24 { get; set; }
        public string Obligacion2 { get; set; }
        public string Entidadinformante2 { get; set; }
        public string TipoObliga2 { get; set; }
        public string GarantiaObliga2 { get; set; }
        public string NumeroObliga2 { get; set; }
        public string FchapertuaObliga2 { get; set; }
        public string FchvencObliga2 { get; set; }
        public string FchactualizacionObliga2 { get; set; }
        public string PeriodoPagoObliga2 { get; set; }
        public string ClasificacionComporta2 { get; set; }
        public string MonedaComporta2 { get; set; }
        public string EstadoComporta2 { get; set; }
        public string LimiteComporta2 { get; set; }
        public string SaldoactualComporta2 { get; set; }
        public string SaldomoraComporta2 { get; set; }
        public string CuotaComporta2 { get; set; }
        public string Vectorhisto2Anio { get; set; }
        public string Vectorhisto2Anio1 { get; set; }
        public string Vectorhisto2Anio2 { get; set; }
        public string Vectorhisto2Anio3 { get; set; }
        public string Vectorhisto2Anio4 { get; set; }
        public string Vectorhisto2Anio5 { get; set; }
        public string Vectorhisto2Anio6 { get; set; }
        public string Vectorhisto2Anio7 { get; set; }
        public string Vectorhisto2Anio8 { get; set; }
        public string Vectorhisto2Anio9 { get; set; }
        public string Vectorhisto2Anio10 { get; set; }
        public string Vectorhisto2Anio11 { get; set; }
        public string Vectorhisto2Anio12 { get; set; }
        public string Vectorhisto2Anio13 { get; set; }
        public string Vectorhisto2Anio14 { get; set; }
        public string Vectorhisto2Anio15 { get; set; }
        public string Vectorhisto2Anio16 { get; set; }
        public string Vectorhisto2Anio17 { get; set; }
        public string Vectorhisto2Anio18 { get; set; }
        public string Vectorhisto2Anio19 { get; set; }
        public string Vectorhisto2Anio20 { get; set; }
        public string Vectorhisto2Anio21 { get; set; }
        public string Vectorhisto2Anio22 { get; set; }
        public string Vectorhisto2Anio23 { get; set; }
        public string Vectorhisto2Anio24 { get; set; }
        public string Vectorhisto2Mes1 { get; set; }
        public string Vectorhisto2Mes2 { get; set; }
        public string Vectorhisto2Mes3 { get; set; }
        public string Vectorhisto2Mes4 { get; set; }
        public string Vectorhisto2Mes5 { get; set; }
        public string Vectorhisto2Mes6 { get; set; }
        public string Vectorhisto2Mes7 { get; set; }
        public string Vectorhisto2Mes8 { get; set; }
        public string Vectorhisto2Mes9 { get; set; }
        public string Vectorhisto2Mes10 { get; set; }
        public string Vectorhisto2Mes11 { get; set; }
        public string Vectorhisto2Mes12 { get; set; }
        public string Vectorhisto2Mes13 { get; set; }
        public string Vectorhisto2Mes14 { get; set; }
        public string Vectorhisto2Mes15 { get; set; }
        public string Vectorhisto2Mes16 { get; set; }
        public string Vectorhisto2Mes17 { get; set; }
        public string Vectorhisto2Mes18 { get; set; }
        public string Vectorhisto2Mes19 { get; set; }
        public string Vectorhisto2Mes20 { get; set; }
        public string Vectorhisto2Mes21 { get; set; }
        public string Vectorhisto2Mes22 { get; set; }
        public string Vectorhisto2Mes23 { get; set; }
        public string Vectorhisto2Mes24 { get; set; }
        public string Obligacion3 { get; set; }
        public string Entidadinformante3 { get; set; }
        public string TipoObliga3 { get; set; }
        public string GarantiaObliga3 { get; set; }
        public string NumeroObliga3 { get; set; }
        public string FchapertuaObliga3 { get; set; }
        public string FchvencObliga3 { get; set; }
        public string FchactualizacionObliga3 { get; set; }
        public string PeriodoPagoObliga3 { get; set; }
        public string ClasificacionComporta3 { get; set; }
        public string MonedaComporta3 { get; set; }
        public string EstadoComporta3 { get; set; }
        public string LimiteComporta3 { get; set; }
        public string SaldoactualComporta3 { get; set; }
        public string SaldomoraComporta3 { get; set; }
        public string CuotaComporta3 { get; set; }
        public string Vectorhisto3Anio { get; set; }
        public string Vectorhisto3Anio1 { get; set; }
        public string Vectorhisto3Anio2 { get; set; }
        public string Vectorhisto3Anio3 { get; set; }
        public string Vectorhisto3Anio4 { get; set; }
        public string Vectorhisto3Anio5 { get; set; }
        public string Vectorhisto3Anio6 { get; set; }
        public string Vectorhisto3Anio7 { get; set; }
        public string Vectorhisto3Anio8 { get; set; }
        public string Vectorhisto3Anio9 { get; set; }
        public string Vectorhisto3Anio10 { get; set; }
        public string Vectorhisto3Anio11 { get; set; }
        public string Vectorhisto3Anio12 { get; set; }
        public string Vectorhisto3Anio13 { get; set; }
        public string Vectorhisto3Anio14 { get; set; }
        public string Vectorhisto3Anio15 { get; set; }
        public string Vectorhisto3Anio16 { get; set; }
        public string Vectorhisto3Anio17 { get; set; }
        public string Vectorhisto3Anio18 { get; set; }
        public string Vectorhisto3Anio19 { get; set; }
        public string Vectorhisto3Anio20 { get; set; }
        public string Vectorhisto3Anio21 { get; set; }
        public string Vectorhisto3Anio22 { get; set; }
        public string Vectorhisto3Anio23 { get; set; }
        public string Vectorhisto3Anio24 { get; set; }
        public string Vectorhisto3Mes1 { get; set; }
        public string Vectorhisto3Mes2 { get; set; }
        public string Vectorhisto3Mes3 { get; set; }
        public string Vectorhisto3Mes4 { get; set; }
        public string Vectorhisto3Mes5 { get; set; }
        public string Vectorhisto3Mes6 { get; set; }
        public string Vectorhisto3Mes7 { get; set; }
        public string Vectorhisto3Mes8 { get; set; }
        public string Vectorhisto3Mes9 { get; set; }
        public string Vectorhisto3Mes10 { get; set; }
        public string Vectorhisto3Mes11 { get; set; }
        public string Vectorhisto3Mes12 { get; set; }
        public string Vectorhisto3Mes13 { get; set; }
        public string Vectorhisto3Mes14 { get; set; }
        public string Vectorhisto3Mes15 { get; set; }
        public string Vectorhisto3Mes16 { get; set; }
        public string Vectorhisto3Mes17 { get; set; }
        public string Vectorhisto3Mes18 { get; set; }
        public string Vectorhisto3Mes19 { get; set; }
        public string Vectorhisto3Mes20 { get; set; }
        public string Vectorhisto3Mes21 { get; set; }
        public string Vectorhisto3Mes22 { get; set; }
        public string Vectorhisto3Mes23 { get; set; }
        public string Vectorhisto3Mes24 { get; set; }
        public string EstadocivConyugue { get; set; }
        public string EstadocivfchConyugue { get; set; }
        public string NombreConyugue { get; set; }
        public string DireccionConyugue { get; set; }
        public string Divisiongeso1Conyugue { get; set; }
        public string Divisiongeso2Conyugue { get; set; }
        public string TelCodConyugue { get; set; }
        public string TelConyugue { get; set; }
        public string IdenCodConyugue { get; set; }
        public string IdenConyugue { get; set; }
    }
}
